### ISSUE TITLE
SQLiteDatabaseCorruptException: file is encrypted or is not a database (code 26)

### ISSUE THREAD

**Issue by peshkira** [Jearil/SimpleNoSQL#41]
In certain cases I get reports of the following error, however, I am unable to reproduce it reliably right now. I am not sure if it has to do directly with this library, but I am using it in my project. I do not have file encryption.

Does this happen for someone else as well, by any chance. Do you have a clue, of it is caused by the library, or if it is an error of SQLLite or the android file system.

According to this: https://sqlite.org/rescode.html#notadb the db file was not existing, which shouldn't be the case.

```
2018-11-19 10:48:30.751 12786-12859/? E/AndroidRuntime: FATAL EXCEPTION: Thread-13
    Process: com.fluidtime.android.fluidhub.ubigo.dev, PID: 12786
    android.database.sqlite.SQLiteDatabaseCorruptException: file is encrypted or is not a database (code 26)
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:599)
        at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
        at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
        at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:842)
        at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:830)
        at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:940)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:311)
        at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:262)
        at com.colintmiller.simplenosql.db.SimpleNoSQLDBHelper.getEntities(SimpleNoSQLDBHelper.java:116)
        at com.colintmiller.simplenosql.db.SimpleNoSQLDBHelper.getEntities(SimpleNoSQLDBHelper.java:107)
        at com.colintmiller.simplenosql.threading.DataDispatcher.retrieve(DataDispatcher.java:121)
        at com.colintmiller.simplenosql.threading.DataDispatcher.run(DataDispatcher.java:83)
```

**Comment by Jearil** [comment]
I've not seen that. Is it on a device or emulator? Does it happen in the wild or are you just locally testing? The system should automatically create a DB file when first running.
